# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Set up OpenGL
      run: |
        sudo add-apt-repository ppa:kisak/kisak-mesa
        sudo apt update
        sudo apt upgrade
        sudo apt-get install xvfb mesa-utils
        xvfb-run glxinfo
    - name: Install dependencies
      run: |
        make requirements
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
